# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: 
      - main
  schedule:
      - cron: "0 0 * * *"

jobs:
  Crawl:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get chromedriver
      run: |
        wget -O ./LATEST_RELEASE http://chromedriver.storage.googleapis.com/LATEST_RELEASE && \
        latest=$(cat ./LATEST_RELEASE) && \
        wget -O ./chromedriver.zip "http://chromedriver.storage.googleapis.com/"$latest"/chromedriver_linux64.zip" && \
        unzip -o chromedriver -d ./
    - name: Install dependencies
      run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Crawl
      run: python crawler.py
    - name: Combine data
      run: python ./Tableau/combine.py
    - name: Clean
      run: rm chromedriver.zip chromedriver LATEST_RELEASE
    - name: Update
      run: |
        now=`date`
        git config --global http.version HTTP/1.1
        git config --global user.name "Bot"
        git config --global user.email 'ndkhoa0704@gmail.com'
        git add ./data
        git commit -m "[ci skip] update ${now}" || echo 'Nothing to commit'
        git push || echo 'Nothing to push'

